# Generated by Django 5.1.6 on 2025-04-28 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_hobbies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='hobbies',
        ),
    ]
