# Generated by Django 5.1.6 on 2025-05-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
